source 'https://rubygems.org'

gemspec


group :jekyll_plugins do
    gem 'jekyll', '3.2'
    gem 'jekyll-tagging', git: 'https://github.com/pattex/jekyll-tagging.git' # https://github.com/pattex/jekyll-tagging/issues/56 # '~> 1.0.1'
end